version: '2'
exclude_patterns:
  - '.next/'
  - 'node_modules/'
  - 'config/'
  - '__tests__'
  - '**/*.test.*'
  # glue code should be ignored:
  - 'pages/_app.tsx'
  - 'pages/_document.tsx'

checks:
  method-lines:
    config:
      threshold: 50

---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 75
