name: changelog
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - name: Create changelog
        run: |
          git config --global user.email "matiasfornes@gmail.com"
          git config --global user.name "Mati"
          npm install -g yarn
          yarn install
          yarn release
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
