name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: npm install -g yarn
      - run: yarn install
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: yarn test:coverage
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
